src/Margo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (
    login_page,
    register_page,
    register_page_2
)
from .views import home_page, contact_page


urlpatterns = [
    url(r'^home/$', home_page, name='home'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', register_page,name='register'),
    url(r'^register-2/$', register_page_2,name='register-2'),
    url(r'^bank/', include('banks.urls', namespace='banks')),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^paym/', include('paymargo.urls', namespace='paymargo')),
    url(r'^members/', include('member.urls', namespace='members')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^api/status/', include('status.api.urls', namespace='status')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/member/urls.py
from django.conf.urls import url

from .views import (
    MemberListView,
    MemberDetailView,
    # MemberDetailSlugView
)

urlpatterns = [
    url(r'^$', MemberListView.as_view(), name='list'),
    url(r'^(?P<username>[\w-]+)/$', MemberDetailView.as_view(), name='detail'),
    # url(r'^(?P<slug>[\w-]+)/$', MemberDetailSlugView.as_view(), name='detail'),
]

src/search/urls.py
from django.conf.urls import url

from .views import (
    SearchMemberListView,

)

urlpatterns = [
    url(r'^$', SearchMemberListView.as_view(), name='query'),
]

src/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous">

<!--Font awesome CSS-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
      crossorigin="anonymous">

src/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'search:query' as search_url%}
{% url 'members:list' as member_list_url%}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">
            <img src="http://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            {% if brand_name %} {{ brand_name }} {% else %} Margo {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contactanos</a>
                </li>
                <li class="nav-item {% if request.path == search_url %} active {% endif %}">
                    <a class="nav-link" href="{{ search_url }}">Enviar</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
                        <a class="nav-link" href="{{ logout_url }}">Cerrar sesión</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Iniciar sesión</a>
                    </li>
                    <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                        <a class="nav-link" href="{{ register_url }}">Registrarse</a>
                    </li>
                {% endif %}
                <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
                    <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fas fa-exchange-alt"></i></a>
                </li>

            </ul>
{#            {% include 'search/snippets/search-form.html' %}#}
        </div>
    </div>
</nav>