src/Margo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (
    login_page,
    register_page,
    register_page_2
)
from .views import home_page, contact_page


urlpatterns = [
    url(r'^home/$', home_page, name='home'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^$', login_page, name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', register_page,name='register'),
    url(r'^register-2/$', register_page_2,name='register-2'),
    url(r'^bank/', include('banks.urls', namespace='banks')),
    url(r'^cart/', include('carts.urls', namespace='cart')),
    url(r'^paym/', include('paymargo.urls', namespace='paymargo')),
    url(r'^members/', include('member.urls', namespace='members')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^api/status/', include('status.api.urls', namespace='status')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/banks/urls.py
from django.conf.urls import url

from .views import (
    bank_home,
    add_bank,
)

urlpatterns = [
    url(r'^$', bank_home, name='home'),
    # url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^add/$', add_bank, name='add'),
    # url(r'^update/$', cart_update, name='update'),
    # url(r'^remove/$', remove_cart, name='remove'),

]

src/banks/models.py
from django.db import models

from member.models import Member


ACCOUNT_TYPES = (
    ('checking', 'Checking'),
    ('savings', 'Savings'),
)

BANK_NAMES = (
    ('Pacifico', 'Pacifico'),
    ('Produbanco', 'Produbanco'),
    ('Bolivariano', 'Bolivariano'),
    ('Guayaquil', 'Guayaquil'),
    ('Internacional', 'Internacional'),
    ('Pichincha', 'Pichincha'),
)


class BankAccount(models.Model):
    user            = models.ForeignKey(Member, null=True)
    nickname        = models.CharField(max_length=120, blank=True, null=True)
    bank_name       = models.CharField(max_length=120, choices=BANK_NAMES)
    account_type    = models.CharField(max_length=120, choices=ACCOUNT_TYPES)
    account_number  = models.CharField(max_length=15)
    valid           = models.BooleanField(default=False)

    def __str__(self):
        if self.nickname:
            return self.nickname.title()
        return self.account_number

    def get_account_number(self):
        acc_num = str(self.account_number)
        return "***" + acc_num[-4:]

src/banks/forms.py
from django import forms

from .models import BankAccount

ACCOUNT_TYPES = (
    ('checking', 'Checking'),
    ('savings', 'Savings'),
)

BANK_NAMES = (
    ('Pacifico', 'Pacifico'),
    ('Produbanco', 'Produbanco'),
    ('Bolivariano', 'Bolivariano'),
    ('Guayaquil', 'Guayaquil'),
    ('Internacional', 'Internacional'),
    ('Pichincha', 'Pichincha'),
)


class AddBankAccountForm(forms.Form):
    bank_name = forms.ChoiceField(
        label='Nombre del banco',
        widget=forms.Select,
        choices= BANK_NAMES,
        )

    nickname = forms.CharField(
        label="Apodo de la cuenta (opcional)",
        max_length=50,
        required=False
    )

    account_type = forms.ChoiceField(
        label='Tipo de cuenta',
        widget= forms.Select,
        choices=ACCOUNT_TYPES
        )

    account_number = forms.CharField(
        label='Numero de cuenta',
        max_length=50,
        )

    def clean_account_number(self):
        an = self.cleaned_data.get('account_number')
        bn = self.cleaned_data.get('bank_name')
        qs = BankAccount.objects.filter(bank_name=bn, account_number=an)
        if qs.exists():
            raise forms.ValidationError("Cuenta ya en uso")
        return an

    def clean_bank_name(self):
        bn = self.cleaned_data.get('bank_name')
        return bn

    def clean_account_type(self):
        at = self.cleaned_data.get('account_type')
        return at

    def clean_nickname(self):
        nn = self.cleaned_data.get('nickname')
        return nn.title()

src/banks/views.py
from django.shortcuts import render, redirect

from .forms import AddBankAccountForm
from . models import BankAccount
from member.models import Member


def bank_home(request):
    user= request.user
    if user.is_authenticated():
        member = Member.objects.get(username=user.get_username())
        bank_obj = BankAccount.objects.filter(user=member)
        context = {
            'bank_obj': bank_obj
        }
        return render(request, 'banks/home.html', context)
    else:
        return redirect('login')


def add_bank(request):
    user = request.user
    if user.is_authenticated():
        member = Member.objects.get(username=user.get_username())
        bank_obj = BankAccount.objects.filter(user=member)

        form = AddBankAccountForm(request.POST or None)

        context = {
            'bank_obj': bank_obj,
            'form': form
        }
        if form.is_valid():
            bn = form.cleaned_data.get('bank_name')
            nn = form.cleaned_data.get('nickname')
            at = form.cleaned_data.get('account_type')
            an = form.cleaned_data.get('account_number')
            BankAccount.objects.create(user=member, nickname=nn, bank_name=bn, account_type=at, account_number=an)
            return redirect('banks:home')
        return render(request, 'banks/add-account.html', context)
    else:
        return redirect("login")

src/banks/templates/banks/add-account.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col py-3 mx-auto">
                <h1>Añadir cuenta bancaria</h1>
                <hr/>
                <form method="POST">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn-success btn-lg">Add</button>

                </form>
            </div>
        </div>
    </div>


{% endblock %}

src/banks/templates/banks/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static "css/main.css" %}">


        <div class="row">
            <div class="col">
            <h1>Cuentas Bancarias</h1>
            {% if bank_obj == None %}
                No hay ninguna cuenta aun.
            {% else %}
                {% for obj in bank_obj %}
                    <h3 style="color: brown">{{ obj.bank_name }}<br></h3>
                    {% if obj.nickname %} {{ obj.nickname }}<br/> {% endif %}
                    {{ obj.get_account_number }}<br/>
                {% endfor %}
            {% endif %}
            </div>
        </div>
        <div class="col">
            <div class="bottom-align">
                <a href="{% url 'banks:add' %}" type="button" class="btn btn-info btn-lg btn-block">Add Bank account</a>
            </div>
        </div>


{% endblock %}